include:
  - project: 'orderlynetwork/orderly-devops/orderly-common/common-ci'
    ref: main
    file: '/common-orderly-network-dev-v2.yaml'
  - project: 'orderlynetwork/orderly-fe/common-ci'
    ref: main
    file: '/frontend-ci.yaml'


variables:
  SERVICE_NAME: official-website
  IMAGE_NAME: official-website


build_docker:
  extends: .build_docker_base
  before_script:
    - !reference [.build_docker_base, before_script]   
    - >-
      export BUILD_ARGS_KV="PARTNERSHIPS_TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      PARTNERSHIPS_TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      BEEHIIV_API_KEY=${BEEHIIV_API_KEY}"
