export const data = [
  {
    id: 159,
    attributes: {
      title: "We Sponsored Sir Otterly’s Frens at the IOSF 🦦🎗️",
      description: "Because Otters Deserve to Thrive—Both in Water and DeFi!",
      slug: "orderly-network-iosf-corporate-sponsorship",
      createdAt: "2024-08-28T08:35:09.686Z",
      updatedAt: "2024-08-28T13:04:09.087Z",
      publishedAt: "2024-08-28T12:52:11.455Z",
      postedTime: "2024-08-28T13:00:00.000Z",
      pin: null,
      cover: {
        data: {
          id: 377,
          attributes: {
            name: "iosf (1).jpg",
            alternativeText: null,
            url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/iosf_1_d19e5c7b2a.jpg",
            formats: {
              large: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/large_iosf_1_d19e5c7b2a.jpg",
                hash: "large_iosf_1_d19e5c7b2a",
                mime: "image/jpeg",
                name: "large_iosf (1).jpg",
                path: null,
                size: 76.32,
                width: 1000,
                height: 563,
                sizeInBytes: 76320,
              },
              small: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/small_iosf_1_d19e5c7b2a.jpg",
                hash: "small_iosf_1_d19e5c7b2a",
                mime: "image/jpeg",
                name: "small_iosf (1).jpg",
                path: null,
                size: 28.3,
                width: 500,
                height: 281,
                sizeInBytes: 28296,
              },
              medium: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/medium_iosf_1_d19e5c7b2a.jpg",
                hash: "medium_iosf_1_d19e5c7b2a",
                mime: "image/jpeg",
                name: "medium_iosf (1).jpg",
                path: null,
                size: 50.63,
                width: 750,
                height: 422,
                sizeInBytes: 50628,
              },
              thumbnail: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/thumbnail_iosf_1_d19e5c7b2a.jpg",
                hash: "thumbnail_iosf_1_d19e5c7b2a",
                mime: "image/jpeg",
                name: "thumbnail_iosf (1).jpg",
                path: null,
                size: 8.97,
                width: 245,
                height: 138,
                sizeInBytes: 8966,
              },
            },
          },
        },
      },
      category: {
        data: {
          id: 2,
          attributes: {
            name: "Educational",
            slug: "Educational",
          },
        },
      },
    },
  },
  {
    id: 158,
    attributes: {
      title: "ORDER is Live! Staking Begins!",
      description: "Put your token to use: Stake $ORDER!",
      slug: "orderly-network-staking-unstake-ORDER",
      createdAt: "2024-08-23T14:22:37.540Z",
      updatedAt: "2024-09-03T03:46:39.180Z",
      publishedAt: "2024-08-26T07:40:41.731Z",
      postedTime: "2024-08-26T11:00:00.000Z",
      pin: true,
      cover: {
        data: {
          id: 376,
          attributes: {
            name: "TGE blog2.jpg",
            alternativeText: null,
            url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/TGE_blog2_05a9c0d85e.jpg",
            formats: {
              large: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/large_TGE_blog2_05a9c0d85e.jpg",
                hash: "large_TGE_blog2_05a9c0d85e",
                mime: "image/jpeg",
                name: "large_TGE blog2.jpg",
                path: null,
                size: 54.8,
                width: 1000,
                height: 563,
                sizeInBytes: 54798,
              },
              small: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/small_TGE_blog2_05a9c0d85e.jpg",
                hash: "small_TGE_blog2_05a9c0d85e",
                mime: "image/jpeg",
                name: "small_TGE blog2.jpg",
                path: null,
                size: 17.71,
                width: 500,
                height: 281,
                sizeInBytes: 17710,
              },
              medium: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/medium_TGE_blog2_05a9c0d85e.jpg",
                hash: "medium_TGE_blog2_05a9c0d85e",
                mime: "image/jpeg",
                name: "medium_TGE blog2.jpg",
                path: null,
                size: 33.77,
                width: 750,
                height: 422,
                sizeInBytes: 33770,
              },
              thumbnail: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/thumbnail_TGE_blog2_05a9c0d85e.jpg",
                hash: "thumbnail_TGE_blog2_05a9c0d85e",
                mime: "image/jpeg",
                name: "thumbnail_TGE blog2.jpg",
                path: null,
                size: 5.89,
                width: 245,
                height: 138,
                sizeInBytes: 5888,
              },
            },
          },
        },
      },
      category: {
        data: {
          id: 5,
          attributes: {
            name: "Announcements",
            slug: "Announcements",
          },
        },
      },
    },
  },
  {
    id: 157,
    attributes: {
      title:
        "Orderly Network and Very Long Swap To Expand Web3 Frontiers in Asian Markets, Introduces First-ever Japanese-built PerpDEX ",
      description:
        "Japanese-based builders to deliver omnichain perps trading, powered by Orderly\n",
      slug: "orderly-network-vls-perp-asia",
      createdAt: "2024-08-23T09:12:47.912Z",
      updatedAt: "2024-08-23T09:53:16.772Z",
      publishedAt: "2024-08-23T09:53:16.764Z",
      postedTime: "2024-08-23T10:00:00.000Z",
      pin: null,
      cover: {
        data: {
          id: 370,
          attributes: {
            name: "Partnerqship.png",
            alternativeText: null,
            url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/Partnerqship_c312f4a9f7.png",
            formats: {
              large: {
                ext: ".png",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/large_Partnerqship_c312f4a9f7.png",
                hash: "large_Partnerqship_c312f4a9f7",
                mime: "image/png",
                name: "large_Partnerqship.png",
                path: null,
                size: 1164.97,
                width: 1000,
                height: 563,
                sizeInBytes: 1164971,
              },
              small: {
                ext: ".png",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/small_Partnerqship_c312f4a9f7.png",
                hash: "small_Partnerqship_c312f4a9f7",
                mime: "image/png",
                name: "small_Partnerqship.png",
                path: null,
                size: 296.78,
                width: 500,
                height: 281,
                sizeInBytes: 296780,
              },
              medium: {
                ext: ".png",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/medium_Partnerqship_c312f4a9f7.png",
                hash: "medium_Partnerqship_c312f4a9f7",
                mime: "image/png",
                name: "medium_Partnerqship.png",
                path: null,
                size: 658.12,
                width: 750,
                height: 422,
                sizeInBytes: 658120,
              },
              thumbnail: {
                ext: ".png",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/thumbnail_Partnerqship_c312f4a9f7.png",
                hash: "thumbnail_Partnerqship_c312f4a9f7",
                mime: "image/png",
                name: "thumbnail_Partnerqship.png",
                path: null,
                size: 77.8,
                width: 245,
                height: 138,
                sizeInBytes: 77798,
              },
            },
          },
        },
      },
      category: {
        data: {
          id: 5,
          attributes: {
            name: "Announcements",
            slug: "Announcements",
          },
        },
      },
    },
  },
  {
    id: 156,
    attributes: {
      title:
        "1 Million Messages: Orderly’s LayerZero Achievement (Who’s Counting?)",
      description: "We are announcing a celebration of epic proportions!",
      slug: "orderly-network-layerzero-campaign",
      createdAt: "2024-08-22T10:12:03.997Z",
      updatedAt: "2024-08-22T15:47:37.256Z",
      publishedAt: "2024-08-22T12:49:40.515Z",
      postedTime: "2024-08-22T12:00:55.142Z",
      pin: null,
      cover: {
        data: {
          id: 368,
          attributes: {
            name: "Poster 2-3.png",
            alternativeText: null,
            url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/Poster_2_3_a08f2b67d7.png",
            formats: {
              large: {
                ext: ".png",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/large_Poster_2_3_a08f2b67d7.png",
                hash: "large_Poster_2_3_a08f2b67d7",
                mime: "image/png",
                name: "large_Poster 2-3.png",
                path: null,
                size: 1143.64,
                width: 1000,
                height: 563,
                sizeInBytes: 1143636,
              },
              small: {
                ext: ".png",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/small_Poster_2_3_a08f2b67d7.png",
                hash: "small_Poster_2_3_a08f2b67d7",
                mime: "image/png",
                name: "small_Poster 2-3.png",
                path: null,
                size: 315.94,
                width: 500,
                height: 281,
                sizeInBytes: 315935,
              },
              medium: {
                ext: ".png",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/medium_Poster_2_3_a08f2b67d7.png",
                hash: "medium_Poster_2_3_a08f2b67d7",
                mime: "image/png",
                name: "medium_Poster 2-3.png",
                path: null,
                size: 669.28,
                width: 750,
                height: 422,
                sizeInBytes: 669284,
              },
              thumbnail: {
                ext: ".png",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/thumbnail_Poster_2_3_a08f2b67d7.png",
                hash: "thumbnail_Poster_2_3_a08f2b67d7",
                mime: "image/png",
                name: "thumbnail_Poster 2-3.png",
                path: null,
                size: 85.62,
                width: 245,
                height: 138,
                sizeInBytes: 85615,
              },
            },
          },
        },
      },
      category: {
        data: {
          id: 5,
          attributes: {
            name: "Announcements",
            slug: "Announcements",
          },
        },
      },
    },
  },
  {
    id: 153,
    attributes: {
      title:
        "Orderly Network Welcomes Zotto, AI-Powered Automated Trading Platform For Onchain Perpetual Trading",
      description:
        "Perps Trading Simplified with Smart AI Agents on Zotto, powered by Orderly",
      slug: "orderly-network-zotto-ai-perps-trading",
      createdAt: "2024-08-13T23:33:30.213Z",
      updatedAt: "2024-08-15T12:58:16.578Z",
      publishedAt: "2024-08-15T12:53:35.912Z",
      postedTime: "2024-08-15T13:00:00.000Z",
      pin: null,
      cover: {
        data: {
          id: 340,
          attributes: {
            name: "zott1o.jpg",
            alternativeText: null,
            url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/zott1o_7105ec97d8.jpg",
            formats: {
              large: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/large_zott1o_7105ec97d8.jpg",
                hash: "large_zott1o_7105ec97d8",
                mime: "image/jpeg",
                name: "large_zott1o.jpg",
                path: null,
                size: 62.89,
                width: 1000,
                height: 563,
                sizeInBytes: 62890,
              },
              small: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/small_zott1o_7105ec97d8.jpg",
                hash: "small_zott1o_7105ec97d8",
                mime: "image/jpeg",
                name: "small_zott1o.jpg",
                path: null,
                size: 22.92,
                width: 500,
                height: 281,
                sizeInBytes: 22921,
              },
              medium: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/medium_zott1o_7105ec97d8.jpg",
                hash: "medium_zott1o_7105ec97d8",
                mime: "image/jpeg",
                name: "medium_zott1o.jpg",
                path: null,
                size: 41.15,
                width: 750,
                height: 422,
                sizeInBytes: 41151,
              },
              thumbnail: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/thumbnail_zott1o_7105ec97d8.jpg",
                hash: "thumbnail_zott1o_7105ec97d8",
                mime: "image/jpeg",
                name: "thumbnail_zott1o.jpg",
                path: null,
                size: 7.45,
                width: 245,
                height: 138,
                sizeInBytes: 7446,
              },
            },
          },
        },
      },
      category: {
        data: {
          id: 5,
          attributes: {
            name: "Announcements",
            slug: "Announcements",
          },
        },
      },
    },
  },
  {
    id: 154,
    attributes: {
      title: "Orderly Soundbites: A Slogan to Rule 'Em All",
      description: "Calling all creatives, thinkers, and wordsmiths! 📣",
      slug: "orderly-network-theme-contest",
      createdAt: "2024-08-14T00:19:09.579Z",
      updatedAt: "2024-08-15T11:54:49.891Z",
      publishedAt: "2024-08-15T11:50:30.483Z",
      postedTime: "2024-08-15T12:00:00.000Z",
      pin: null,
      cover: {
        data: {
          id: 349,
          attributes: {
            name: "sound.jpg",
            alternativeText: null,
            url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/sound_146d1f0e07.jpg",
            formats: {
              large: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/large_sound_146d1f0e07.jpg",
                hash: "large_sound_146d1f0e07",
                mime: "image/jpeg",
                name: "large_sound.jpg",
                path: null,
                size: 91.28,
                width: 1000,
                height: 563,
                sizeInBytes: 91280,
              },
              small: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/small_sound_146d1f0e07.jpg",
                hash: "small_sound_146d1f0e07",
                mime: "image/jpeg",
                name: "small_sound.jpg",
                path: null,
                size: 28.21,
                width: 500,
                height: 281,
                sizeInBytes: 28205,
              },
              medium: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/medium_sound_146d1f0e07.jpg",
                hash: "medium_sound_146d1f0e07",
                mime: "image/jpeg",
                name: "medium_sound.jpg",
                path: null,
                size: 56.39,
                width: 750,
                height: 422,
                sizeInBytes: 56389,
              },
              thumbnail: {
                ext: ".jpg",
                url: "https://exuberant-sparkle-dc686d5c20.media.strapiapp.com/thumbnail_sound_146d1f0e07.jpg",
                hash: "thumbnail_sound_146d1f0e07",
                mime: "image/jpeg",
                name: "thumbnail_sound.jpg",
                path: null,
                size: 9.07,
                width: 245,
                height: 138,
                sizeInBytes: 9070,
              },
            },
          },
        },
      },
      category: {
        data: {
          id: 5,
          attributes: {
            name: "Announcements",
            slug: "Announcements",
          },
        },
      },
    },
  },
];
